# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rpg_resources/item_information.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(297, 235)
        self.item_icon = QtWidgets.QPushButton(Dialog)
        self.item_icon.setGeometry(QtCore.QRect(10, 10, 61, 61))
        self.item_icon.setAutoFillBackground(True)
        self.item_icon.setStyleSheet("")
        self.item_icon.setText("")
        self.item_icon.setIconSize(QtCore.QSize(41, 41))
        self.item_icon.setAutoDefault(True)
        self.item_icon.setFlat(False)
        self.item_icon.setObjectName("item_icon")
        self.equip_button = QtWidgets.QPushButton(Dialog)
        self.equip_button.setGeometry(QtCore.QRect(210, 200, 75, 23))
        self.equip_button.setObjectName("equip_button")
        self.destroy_button = QtWidgets.QPushButton(Dialog)
        self.destroy_button.setGeometry(QtCore.QRect(130, 200, 75, 23))
        self.destroy_button.setObjectName("destroy_button")
        self.name_label = QtWidgets.QLabel(Dialog)
        self.name_label.setGeometry(QtCore.QRect(80, 10, 41, 16))
        self.name_label.setObjectName("name_label")
        self.modifiers_label = QtWidgets.QLabel(Dialog)
        self.modifiers_label.setGeometry(QtCore.QRect(10, 80, 61, 16))
        self.modifiers_label.setObjectName("modifiers_label")
        self.modifiers_value = QtWidgets.QLabel(Dialog)
        self.modifiers_value.setGeometry(QtCore.QRect(10, 100, 271, 91))
        self.modifiers_value.setTextFormat(QtCore.Qt.RichText)
        self.modifiers_value.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.modifiers_value.setObjectName("modifiers_value")
        self.description_value = QtWidgets.QLabel(Dialog)
        self.description_value.setGeometry(QtCore.QRect(80, 30, 201, 51))
        self.description_value.setTextFormat(QtCore.Qt.RichText)
        self.description_value.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.description_value.setObjectName("description_value")
        self.name_value = QtWidgets.QLabel(Dialog)
        self.name_value.setGeometry(QtCore.QRect(130, 10, 41, 16))
        self.name_value.setObjectName("name_value")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.equip_button.setText(_translate("Dialog", "Equip"))
        self.destroy_button.setText(_translate("Dialog", "Destroy"))
        self.name_label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Name:</span></p></body></html>"))
        self.modifiers_label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Modifiers:</span></p></body></html>"))
        self.modifiers_value.setText(_translate("Dialog", "<html><head/><body><p>...</p></body></html>"))
        self.description_value.setText(_translate("Dialog", "<html><head/><body><p>...</p></body></html>"))
        self.name_value.setText(_translate("Dialog", "<html><head/><body><p>Default</p></body></html>"))
